name: Test
on: push
env:
  name: cao cuong
  age: 21
jobs:
  windows_job:
    runs-on: windows-latest
    steps:
      - run: echo ${{ env.name }}
      - run: echo ${{ env.name }}
        env:
          name: dang manh
  linux_job:
    runs-on: ubuntu-latest
    env:
      name: dinh canh
    steps:
      - run: echo ${{ env.name }}